create table if not exists users (
 id bigint generated by default as identity primary key,
 telegram_id bigint unique not null,
 username text,
 first_name text,
 balance numeric(12,2) not null default 0,
 created_at timestamptz not null default now()
);
create table if not exists roles (
 telegram_id bigint primary key,
 role text not null check (role in ('admin','reviewer','moderator')),
 created_at timestamptz not null default now()
);
create table if not exists tasks (
 id bigint generated by default as identity primary key,
 title text not null,
 description text not null,
 reward numeric(12,2) not null,
 active boolean not null default true,
 posted_message_id bigint,
 created_at timestamptz not null default now()
);
create table if not exists submissions (
 id bigint generated by default as identity primary key,
 task_id bigint not null references tasks(id) on delete cascade,
 user_id bigint not null references users(id) on delete cascade,
 proof_urls jsonb not null default '[]'::jsonb,
 note text,
 status text not null default 'pending' check (status in ('pending','approved','rejected')),
 rejection_reason text,
 reward numeric(12,2) not null default 0,
 credited numeric(12,2) not null default 0,
 reviewed_by bigint,
 reviewed_at timestamptz,
 created_at timestamptz not null default now()
);
create table if not exists webhook_events (
 id bigint generated by default as identity primary key,
 event_key text unique not null,
 event_type text not null,
 submission_id bigint,
 payload jsonb not null,
 delivered boolean not null default false,
 created_at timestamptz not null default now()
);
